#!/bin/bash

# Read the command
COMMAND=$1

# Help
if [ $COMMAND = "help" ]
then
	printf "Available commands:\n\tclean - Q.E.D.\n\tpkginst - Installs dependencies.\n\tqt - Grabs the qt5 repository and initialises it.\n\tmini2d - Installs the mini2d plugin.\n\tconfig - Configures QT.\n\tbuild - Runs make.\n\trun <PLATFORM> <EXAMPLE> - Runs the specified example on the specified platform.\n\tcrun <PLATFORM> <EXAMPLE> - Complete clean rerun. Run after at least one regualar usage.\n\n"
	exit 0
fi

# Wipe...
if [ $COMMAND = "clean" ]
then
	sudo rm -fr build
	sudo rm -fr qt5
	printf "\n--- DONE(clean): Removed build/ and qt5/ directories. ---\n\n"
	exit 0
fi


# Dependencies...
if [ $COMMAND = "pkginst" ]
then
	sudo apt install libx11-dev \
		libx11-xcb-dev \
		libxext-dev \
		libxfixes-dev \
		libxi-dev \
		libxrender-dev \
		libxcb1-dev \
		libxcb-glx0-dev libxcb-keysyms1-dev \
		libxcb-image0-dev \
		libxcb-shm0-dev \
		libxcb-icccm4-dev \
		libxcb-sync0-dev \
		libxcb-xfixes0-dev \
		libxcb-shape0-dev \
		libxcb-randr0-dev \
		libxcb-render-util0-dev \
		libxcb-xinerama0-dev \
		libxkbcommon-dev \
		libxkbcommon-x11-dev
	sudo apt install libdirectfb-dev
	printf "\n--- DONE(pkginst): Installed all packages. ---\n\n"
	exit 0
fi

# Qt5...
if [ $COMMAND = "qt" ]
then
	git clone https://code.qt.io/qt/qt5.git
	pushd qt5/
	git checkout 5.15
	perl init-repository --module-subset=qtbase
	popd
	printf "\n--- DONE(qt): Grabbed and initialised Qt5. ---\n\n"
	exit 0
fi

# Our platform...
if [ $COMMAND = "mini2d" ]
then
	unzip mini2d.zip
	mv mini2d qt5/qtbase/src/plugins/platforms
	rm qt5/qtbase/src/plugins/platforms/platforms.pro
	cp platforms.pro qt5/qtbase/src/plugins/platforms
	cat qt5/qtbase/src/plugins/platforms/platforms.pro | grep mini2d
	ls qt5/qtbase/src/plugins/platforms/mini2d/
	printf "\n--- DONE(mini2d): Installed mini2d. ---\n\n"
	exit 0
fi

# Configure Qt...
if [ $COMMAND = "config" ]
then
	mkdir build/
	pushd build/
	FLAGS="-qpa xcb;mini2d;directfb;minimal -xcb"
	../qt5/configure \
		-developer-build \
		-opensource \
		-confirm-license \
		-Dregister= \
		-directfb \
		-nomake tests \
		-no-opengl \
		-no-dbus \
		-no-feature-cups \
		-no-linuxfb \
		-xcb-native-painting \
		$FLAGS
	popd
	printf "\n--- DONE(config): Configured Qt. ---\n\n"
	exit 0
fi

# Build Qt...
if [ $COMMAND = "build" ]
then
	pushd build/
	time make -j8
	popd
	printf "\n--- DONE(build): Make finished. ---\n\n"
	exit 0
fi

# Set up and test examples...
if [ $COMMAND = "run" ]
then
	if [ $# -ne 3 ]
	then
		printf "\n--- No platform or example given. ---\n\n"
		exit 1
	fi
	PLATFORM=$2
	APP_NAME=$3
	printf "\n--- Running $APP_NAME with $PLATFORM. ---\n\n"
	pushd build/
	sudo ls
	APP=./qtbase/examples/widgets/widgets/$APP_NAME/$APP_NAME
	EXAMPLE="$APP -platform"
	export QT_DEBUG_BACKINGSTORE=1
	export QT_QPA_PLATFORMTHEME=gtk3
	sudo bash -c "$EXAMPLE $PLATFORM 2>../qt_err_trace 1>../qt_cout_trace" &
	popd
	exit 0
fi

# Complete rerun after one full normal install...
if [ $COMMAND = "crun" ]
then
	if [ $# -ne 3 ]
	then
		printf "\n--- Platform or example not given. ---\n\n"
		exit 1
	fi
	./skr clean
	./skr qt
	./skr mini2d
	./skr config
	./skr build
	./skr platform $2
	./skr run $3
	exit 0
fi

exit 0

# Run...
# With DirectFB
# sudo $EXAMPLE -platform mini2d &
# Ctrl+Alt+F2
# sudo kill $!

#-platform linuxfb -plugin EvdevMouse -plugin EvdevKeyboard #-style motif
